### ISSUE TITLE
[ 许可证 ] 项目应该使用怎样的许可证？

### ISSUE THREAD

**Issue by ghost** [Things-Before-Coding/Things-Before-Coding-docs#20]
虽然现在就开始讨论许可证的问题有点早，但是不可否认这也是十分重要的一件事。

项目应该使用怎样的许可证？
CC-BY-SA 4.0 ?
GNU FDL ?
......?

**Comment by LaoshuBaby** [comment]
（虽然已经结束多年了，但是最近随着短视频的火爆，看到越来越多身边的同学，非常排斥文字内容，更喜欢跟着B站上一些快餐式的教学对着做）
（倒不是说视频和文字谁更好谁更low，抓到老鼠都是好猫，但是这些视频创作者自身能力，并非所有录课的都是有很强技术功底的，也有人就是对着知乎回答重新翻拍，我不希望我们的项目最后被用作这种翻拍课，然后还被用作去要三连的资本，尤其是投了原创会有创作者激励的情况下）

因此还是希望诸位考虑一下 CC BY-NC-SA 4.0，拿去用了就用了，不过不要拿本项目赚钱，毕竟我们大家也都是纯打白工的在这里准备课程。

（以上是现任独裁者的自言自语，没人回应的话，就依然按照茨月佬的来。主要是这两个许可证不相容，大量开始以后就不能转换了，或者是至少很难转换。）
